config/routes.rb
Rails.application.routes.draw do
  # resources :comments #=> passed to websockets 
  # Custom implementation for devise actions
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  # Custom routes for pages
  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  mount ActionCable.server => '/cable'

  root 'pages#home'
end

app/models/blog.rb
class Blog < ApplicationRecord
  enum status: { draft: 0, published: 1 }
  extend FriendlyId
  friendly_id :title, use: :slugged

  validates_presence_of :title, :body

  belongs_to :topic, optional: true
  has_many :comments, dependent: :destroy
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy, :toggle_status]
  layout "blog"
  access all: [:show, :index], user: {except: [:destroy, :create, :new, :update, :edit]}, site_admin: :all

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.page(params[:page]).per(5)
    @page_title = "My Portfolio Blog"
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    @blog = Blog.includes(:comments).friendly.find(params[:id])
    @comment = Comment.new
    
    @page_title = @blog.title
    @seo_keywords = @blog.body
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit; end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def toggle_status
    if @blog.draft?
      @blog.published!
    elsif @blog.published?
      @blog.draft!
    end
    redirect_to blogs_url, notice: 'Post status has been updated.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :body)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def gravatar_helper user
    size = "?s=200"
    default = "?d=robohash"
    hash = Digest::MD5.hexdigest(user.email.downcase)
    image_tag "https://www.gravatar.com/avatar/#{hash}#{size}#{default}", width: 80
  end
end

app/views/blogs/_blog.html.erb
<div class="blog-post">
  <h2 class="blog-post-title"><%= link_to blog.title.upcase, blog %></h2>
  <p class="blog-post-meta">Published <%= distance_of_time_in_words(blog.created_at, Time.now) %> ago.</p>
  
  <p><%= blog.body %></p>

  <% if logged_in?(:site_admin) %>
    <p class="blog-post-meta">
      <%= link_to blog.status.titleize, toggle_status_blog_path(blog) %> | 
      <%= link_to 'Edit', edit_blog_path(blog) %> | 
      <%= link_to 'Delete Post', blog, method: :delete, data: { confirm: 'Are you sure?' } %>
    </p>
  <% end %>

</div><!-- /.blog-post -->

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <% blog.errors.full_messages.each do |error| %>
      <%= alert_generator error %>
    <% end %>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :body %>
    <%= form.text_area :body, class: 'form-control', rows: 15 %>
  </div>

  <div class="form-group">
    <%= form.submit "Submit", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<div class="col-md-8 blog-main">

  <h2>Edit Blog Post</h2>

  <%= render 'form', blog: @blog %>

  <%= link_to 'Show', @blog %> |
  <%= link_to 'Back', blogs_path %>

</div><!-- /.blog-main -->

app/views/blogs/index.html.erb
<div class="col-md-8 blog-main">
  <h3 class="pb-3 mb-4 font-italic border-bottom">
    From my Head
  </h3>

  <h4>
    <%= link_to 'Write a new Post', new_blog_path if logged_in?(:site_admin) %>
  </h4>

  <br>

  <%= render @blogs %>

  <nav class="blog-pagination">
    <%= paginate @blogs %>
  </nav>

</div><!-- /.blog-main -->

app/views/blogs/new.html.erb
<div class="col-md-8 blog-main">

  <h2>New Blog Post</h2>

  <%= render 'form', blog: @blog %>

  <%= link_to 'Back', blogs_path %>

</div>

app/views/blogs/show.html.erb
<div class="col-md-8 blog-main">

  <h2><%= @blog.title.titleize %></h2>

  <% if logged_in?(:site_admin) %>
    <p class="blog-post-meta">
      <%= link_to 'Edit', edit_blog_path(@blog) %>
    </p>
  <% end %>

  <p><%= @blog.body %></p>

  <hr>

  <%= render 'comments/comment_form' %>

  <div id="comments" data-blog-id="<%= @blog.id %>">
    <%= render @blog.comments %>
  </div>

</div>