config/routes.rb
Rails.application.routes.draw do
  # resources :comments #=> passed to websockets 
  # Custom implementation for devise actions
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  # Custom routes for pages
  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  mount ActionCable.server => '/cable'

  root 'pages#home'
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  has_many :technologies
  has_many_attached :images
  accepts_nested_attributes_for :technologies,
                                allow_destroy: true,
                                reject_if: lambda { |attrs| attrs['name'].blank? }

  include Placeholder
  validates_presence_of :title, :body, :main_image, :thumb_image

  def self.angular_items
    where(subtitle: 'Angular')
  end

  scope :ruby_on_rails_items, -> { where(subtitle: 'Ruby on Rails') } 

  scope :by_position, -> { order("position ASC") }

  after_initialize :set_defaults

  def set_defaults
    self.main_image  ||= Placeholder.image_generator(height: '600', width: '400')
    self.thumb_image ||= Placeholder.image_generator(height: '350', width: '200')
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio, only: [:show, :edit, :update, :destroy]
  layout "portfolio"
  access all: [:show, :index, :angular_items], user: {except: [:destroy, :create, :new, :update, :edit, :sort]}, site_admin: :all

  def index
    @portfolio_items = Portfolio.by_position
  end

  def sort
    params[:order].each do |key, value|
      Portfolio.find(value[:id]).update(position: value[:position])
    end

    render body: nil
  end

  def angular_items
    @angular_portfolio_items = Portfolio.angular_items
  end

  def new
    @portfolio_item = Portfolio.new
  end

  def show; end

  def create
    @portfolio_item = Portfolio.new(portfolios_params)

    respond_to do |format|
      if @portfolio_item.save
        format.html { redirect_to portfolios_path, notice: 'Your portfolio item is now live' }
      else
        format.html { render :new }
      end
    end
  end

  def edit; end

  def update
    respond_to do |format|
      if @portfolio_item.update(portfolios_params)
        format.html { redirect_to portfolios_path, notice: 'The record successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @portfolio_item.destroy
    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: 'Portfolio item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_portfolio
      @portfolio_item = Portfolio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def portfolios_params
      params.require(:portfolio).permit(:title, :subtitle, :body, technologies_attributes: [:id, :name, :_destroy], images: [])
    end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
  def portfolio_image(portfolio_item, style)
    if portfolio_item.images.attached?
      image_tag(portfolio_item.images.first, class: style)
    else
      image_tag(portfolio_item.thumb_image, class: style)
    end
  end
end

app/views/portfolios/_form.html.erb
<%= form_for(@portfolio_item) do |f| %>
  <% if @portfolio_item.errors.any? %>
    <% @portfolio_item.errors.full_messages.each do |error| %>
      <%= alert_generator error %>
    <% end %>
  <% end %>

  <div class="row">
    <div class="col-md-8">
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, class: 'form-control', rows: 15 %>
      </div>
    </div>

    <div class="col-md-4">
      <h2>Image</h2>
      <hr>
      <%= portfolio_image(portfolio_item, 'card-img-top') %>
      <hr>
      <div class="form-group">
        <%= f.file_field :images, multiple: true, class: "form-control" %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <h2>Technologies Used:</h2>
      <hr>

      <div>
        <%= f.fields_for :technologies do |technology_form| %>
          <%= render 'technology_fields', f: technology_form %>
        <% end %>
      </div>

      <div>
        <%= link_to_add_association 'Add Technology', f, :technologies %>
      </div>

      <div class="actions">
        <%= f.submit 'Save Portfolio Item', class: 'btn btn-block btn-primary' %>
      </div>
    </div>
  </div>
<% end %>

app/views/portfolios/_portfolio_item.html.erb
<div class="col-md-4" data-id="<%= portfolio_item.id %>">
  <div class="card mb-4 box-shadow">
    <%= portfolio_image(portfolio_item, 'card-img-top') %>
    <div class="card-body">
      <p class="card-text"><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %></p>
      <p class="card-text"><%= portfolio_item.body.truncate(100) %></p>
      <div class="d-flex justify-content-between align-items-center">
        <% if logged_in?(:site_admin) %>
          <div class="btn-group">
            <%= link_to "Edit", edit_portfolio_path(portfolio_item), class: 'btn btn-sm btn-outline-secondary' %>
            <%= link_to 'Delete', portfolio_path(portfolio_item), class: 'btn btn-sm btn-outline-secondary', method: :delete, data: { confirm: 'Are you sure?' } %>
          </div>
        <% end %>
        <small class="text-muted"><%= distance_of_time_in_words(portfolio_item.created_at, Time.now) %> ago.</small>
      </div>
    </div>
  </div>
</div>

app/views/portfolios/_technology_fields.html.erb
<div class="form-group nested-fields">
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>
  <%= link_to_remove_association 'Remove Tech Item', f %>
</div><%=  %>

app/views/portfolios/edit.html.erb
<div class="container py-5">
  <h1>Edit this Portfolio Item</h1>

  <%= render 'form', portfolio_item: @portfolio_item %>
</div>

app/views/portfolios/index.html.erb
<main role="main">

  <div class="album py-5 bg-light">
    <div class="container">

      <h5><%= link_to "Create New Portfolio Item", new_portfolio_url if logged_in?(:site_admin) %></h5>
      <br>

      <div class="row <%= 'sortable' if logged_in?(:site_admin) %>">
        <%= render partial: 'portfolio_item', collection: @portfolio_items %>
      </div>
      

    </div>
  
  </div>

</main>

app/views/portfolios/new.html.erb
<div class="container py-5">
  <h1>Create a new Portfolio Item</h1>
  
  <%= render 'form', portfolio_item: @portfolio_item %>
</div>

app/views/portfolios/show.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-md-7">
      <%= portfolio_image(@portfolio_item, 'show-image') %>
    </div>
    <div class="col-md-5">
      <h1><%= @portfolio_item.title %></h1>
      <hr>

      <em><%= @portfolio_item.subtitle %></em>
      <p><%= @portfolio_item.body %></p>

      <hr>
      <h5>Technologies Used:</h5>
      <% @portfolio_item.technologies.each do |t| %>
        <p><%= t.name %></p>
      <% end %>
    </div>
  </div>
</div>