config/routes.rb
Rails.application.routes.draw do
  # resources :comments #=> passed to websockets 
  # Custom implementation for devise actions
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  # Custom routes for pages
  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  mount ActionCable.server => '/cable'

  root 'pages#home'
end

app/views/shared/_application_footer.html.erb
<footer class="mastfoot mt-auto app-footer">
  <div class="inner">
    <p><%= copyright_generator %></p>
  </div>
</footer>

app/views/shared/_application_nav.html.erb
<header class="masthead mb-auto">
  <div class="inner">
    <h3 class="masthead-brand">Carlos Gómez</h3>
    <nav class="nav nav-masthead justify-content-center">
      <%= nav_helper(style: 'nav-link', tag_type: '') %>
      <%= login_helper('nav-link') %>
    </nav>
  </div>
</header>

app/views/shared/_blog_big_post.html.erb
<div class="jumbotron p-3 p-md-5 text-white rounded bg-dark">
  <div class="col-md-6 px-0">
    <h1 class="display-4 font-italic">Title of a longer featured blog post</h1>
    <p class="lead my-3">Multiple lines of text that form the lede, informing new readers quickly and efficiently about
      what's most interesting in this post's contents.</p>
    <p class="lead mb-0"><a href="#" class="text-white font-weight-bold">Continue reading...</a></p>
  </div>
</div>

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
  <p><%= copyright_generator %></p>
  <p>
    <a href="#">Back to top</a>
  </p>
</footer>

app/views/shared/_blog_nav.html.erb
<header class="blog-header py-3">
  <div class="row flex-nowrap justify-content-between align-items-center">
    <div class="col-4 pt-1">
      <a class="text-muted" href="#">Subscribe</a>
    </div>
    <div class="col-4 text-center">
      <a class="blog-header-logo text-dark" href="#">Dev Thoughts</a>
    </div>
    <div class="col-4 d-flex justify-content-end align-items-center">
      <a class="text-muted" href="#">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor"
          stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mx-3">
          <circle cx="10.5" cy="10.5" r="7.5"></circle>
          <line x1="21" y1="21" x2="15.8" y2="15.8"></line>
        </svg>
      </a>
      <%= login_helper(style = %w[btn btn-sm btn-outline-secondary fix-btn]) %>
    </div>
  </div>
</header>

app/views/shared/_blog_sidebar.html.erb
<aside class="col-md-4 blog-sidebar">
  <div class="p-3 mb-3 bg-light rounded">
    <h4 class="font-italic">About</h4>
    <p class="mb-0">Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet
      fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
  </div>

  <div class="p-3">
    <h4 class="font-italic">Elsewhere</h4>
    <ol class="list-unstyled">
      <li><a href="#"><%= fa_stacked_icon "github", base: "square-o", text: "Github" %></a></li>
      <li><a href="#"><%= fa_stacked_icon "twitter", base: "square-o", text: "Twitter" %></a></li>
      <li><a href="#"><%= fa_stacked_icon "facebook", base: "square-o", text: "Facebook" %></a></li>
    </ol>
  </div>
</aside><!-- /.blog-sidebar -->

app/views/shared/_blog_topics_nav.html.erb
<div class="nav-scroller py-1 mb-2">
  <nav class="nav d-flex justify-content-between">
    <%= nav_helper(style: 'p-2 text-muted', tag_type: '') %>
  </nav>
</div>

app/views/shared/_meta_layouts.html.erb
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="keywords" content="<%= @seo_keywords %>">

app/views/shared/_nav.html.erb
<div class='<%= location %>'>
  <div><%= link_to "Home", root_path %></div>
  <div><%= link_to "About Me", about_me_path %></div>
  <div><%= link_to "Contact", contact_path %></div>
  <div><%= link_to "Blogs", blogs_path %></div>
  <div><%= link_to "Portfolio", portfolios_path %></div>
</div>

app/views/shared/_portfolio_footer.html.erb
<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <%= link_to 'View all Portfolio Items', portfolios_path %> | 
      <a href="#">Back to top</a>
    </p>
    <p><%= copyright_generator %></p>
  </div>
</footer>

app/views/shared/_portfolio_masthead.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">My Portfolio</h1>
    <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don't simply skip over it entirely.</p>
    <p>
      <a href="#" class="btn btn-primary my-2">See my latest work</a>
      <%= link_to 'Contact me', contact_path, class: 'btn btn-secondary my-2' %>
    </p>
  </div>
</section>

app/views/shared/_portfolio_nav.html.erb
<header>
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">About</h4>
          <p class="text-muted">Add some information about the album below, the author, or any other background
            context. Make it a few sentences long so folks can pick up some informative tidbits. Then, link them off to
            some social networking sites or contact information.</p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4 class="text-white">Navigation</h4>
          <ul class="list-unstyled">
            <%= nav_helper(style: 'text-white', tag_type: 'li') %>
            <li><%= login_helper 'btn btn-sm btn-outline-light fix-btn' %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark box-shadow">
    <div class="container d-flex justify-content-between">
      <%= link_to portfolios_path, class: 'navbar-brand d-flex align-items-center' do %>
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mr-2"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path><circle cx="12" cy="13" r="4"></circle></svg>
        <strong>Carlos Gómez</strong>
      <% end %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>